# Use root/example as user/password credentials
version: '3.1'

networks:
  default:
    external:
      name: webproxy

services:
  postgres:
    container_name: bbb-postgres
    image: postgres:13.1
    restart: always
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    env_file: database.env
  bbb_backend:
    container_name: bbb-backend
    restart: always
    build: rhymin/bbb-backend:LATEST
    env_file: backend.env
    expose:
      - "8080"
    links:
      - postgres