quarkus:
  # configure your datasource
  datasource:
    db-kind: postgresql
    username: ${DB_USER:bbb-backend}
    password: ${DB_PASSWORD:bbb-backend}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/bbb-backend}
  # Flyway minimal config properties
  flyway:
    schemas: public
    migrate-at-start: true
    validate-on-migrate: true
  http:
    access-log:
      enabled: false
    cors:
      ~: true
      methods: GET,POST,DELETE,OPTIONS
      origins: http://localhost:5000, http://localhost:3000
  log:
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: TRACE
# JWT & security
mp:
  jwt:
    verify:
      issuer: https://securetoken.google.com/bachelor-bullshit-bingo
      publickey:
        location: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com